myblog/blog/urls.py
from django.conf.urls import url, handler404, handler500
from blog import views

app_name = 'blog'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'post/all/$', views.PostView.as_view(), name='post'),
    url(r'post/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'post/category/(?P<pk>\d+)/$', views.CategoryView.as_view(), name='category'),
    url(r'post/tag/(?P<pk>\d+)/$', views.TagView.as_view(), name='tag'),

]

handler404 = views.page_not_found
handler500 = views.page_error

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostRessFeed
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^15910/fly-admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^all/rss/$', AllPostRessFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^markdownx/', include('markdownx.urls')),

# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 ]

myblog/users/urls.py
from django.conf.urls import url, include
from users import views
app_name = 'users'


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^account/$', views.user_detail, name='user_detail'),


]

myblog/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
# Create your models here.


class User(AbstractUser):
    # 用户昵称(唯一）
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    avatar = ProcessedImageField(upload_to='avatar',
                                 default='avatar/default.jpg',
                                 processors=[ResizeToFit(80, 80)], verbose_name='用户头像')

    def __str__(self):
        return self.username

    # 用户上传图片放入以账户命名的文件夹下
    def save(self, *args, **kwargs):
        # 用户上传的avatar.name为： '文件名'
        # print(self.avatar.name+'===1===')
        # 拼接出'username/文件名’，调用父类save
        # 便可变为‘upload_to/username/avatar.name
        # 其余情况直接save便可
        if len(self.avatar.name.split('/')) == 1:
            self.avatar.name = self.username+'/' + self.avatar.name
            # print(self.avatar.name+'===2===')

        super(User, self).save()

    class Meta(AbstractUser.Meta):
        pass

myblog/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.forms import ModelForm


# 用户注册表单
class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        # 父类的默认表单控件只有 用户名、密码、确认密码这三个控件
        # （密码和确认密码在 UserCreationForm 的属性中指定）
        # 添加邮箱地址表单控件
        fields = ('username', 'email', 'nickname')


# 用户中心表单
class UserDetailForm(ModelForm):
    class Meta:
        model = User
        fields = ('nickname', 'email', 'avatar')

myblog/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, UserDetailForm
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
# Create your views here.


@require_http_methods(['GET', 'POST'])
def register(request):
    # 获取传递来的next
    # 若为get请求，获取传入来的next 若直接访问，无next，注册成功之后跳转到首页
    # 当注册成功发出post请求时，获取之前get的next
    redirect_to = request.POST.get('next', request.GET.get('next', ))

    # 若用户已登录 跳转到首页
    if request.user.is_authenticated:
        return redirect('/')

    # 请求为POST 表面用户提交了注册信息
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        # 验证数据是否合法
        if form.is_valid():
            # 若合法调用表单save方法将用户数据保存到数据库
            form.save()

            if redirect_to:
                # 注册成功，跳转回之前页面
                return redirect(redirect_to)
    else:
        # 请求不是POST，显示注册页面
        form = RegisterForm()
    # 将get请求传来的next继续传递给模板
    return render(request, 'users/register.html', {'form': form, 'next': redirect_to})


@login_required
def user_detail(request):
    information = ''
    # 若为POST请求，代表用户修改数据
    if request.method == 'POST':

        form = UserDetailForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            information = '修改成功！'

    # 若为GET请求, 显示表单即可
    form = UserDetailForm(instance=request.user)
    return render(request, 'users/user_detail.html', {'form': form, 'information': information})

myblog/templates/users/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block titile %}用户注册{% endblock titile %}

{% block top %}
    <link rel="stylesheet" href="{% static 'blog/css/user/user_style.css' %}">

{% endblock top %}

{% block breadcrumb %}
    <span class="separator">&#x2F;</span>
    <a href="{% url 'users:register' %}">用户注册</a>
{% endblock breadcrumb %}

{% block users %}
<div class="widewrapper main">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 clean-superblock" id="contact">
                <h3>注册</h3>
                <form class="form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                      <button type="submit" class="btn btn-primary btn-block">注册</button>
                    <input type="hidden" name="next" value="{{ next }}">
                </form>
                <div class="login_bottom" style="text-align: center" >
                    <a href="{% url 'login' %}" >已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>






{#<div class="flex-center">#}
{#    <div class="container">#}
{#        <div class="flex-center">#}
{#            <div class="unit-1-2 unit-1-on-mobile">#}
{#                <h3>注册</h3>#}
{#                <form class="form" action="{% url 'users:register' %}" method="post">#}
{#                    {% csrf_token %}#}
{#                    {% for field in form %}#}
{#                        {{ field.label_tag }}#}
{#                        {{ field }}#}
{#                        {{ field.errors }}#}
{#                        {% if field.help_text %}#}
{#                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}


                    <!--用户名-->
{#                    <label for="id_username">用户名:</label>#}
{#                    {{ form.username }}#}
{#                    {{ form.username.errors }}#}
{#                    {% if form.username.help_text %}#}
{#                        <p class="help text-small text-muted">{{ form.username.help_text|safe }}</p>#}
{#                    {% endif %}#}
{##}
{#                    <!--昵称-->#}
{#                    <label for="id_nickname">昵称:</label>#}
{#                    {{ form.nickname }}#}
{#                    {{ form.nickname.errors }}#}
{#                    {% if form.nickname.help_text %}#}
{#                        <p class="help text-small text-muted">{{ form.nickname.help_text|safe }}</p>#}
{#                    {% endif %}#}
{##}
{#                    <!--邮箱值-->#}
{#                    <label for="id_email">电子邮箱地址:</label>#}
{#                    {{ form.email }}#}
{#                    {{ form.email.errors }}#}
{#                    {% if form.email.help_text %}#}
{#                        <p class="help text-small text-muted">{{ form.email.help_text|safe }}</p>#}
{#                    {% endif %}#}
{##}
{#                    <!--密码-->#}
{#                    <label for="id_password1">密码:</label>#}
{#                    {{ form.password1 }}#}
{#                    {{ form.password1.erroprs }}#}
{#                    {% if form.password1.help_text %}#}
{#                        <p class="help text-small text-muted">{{ form.password2.help_text|safe }}</p>#}
{#                    {% endif %}#}
{##}
{#                    <!--确认密码-->#}
{#                    <label for="id_password2">密码确认:</label>#}
{#                    {{ form.password2 }}#}
{#                    {{ form.password2.errors }}#}
{#                    {% if form.password2.help_text %}#}
{#                        <p class="help text-small text-muted">{{ form.password2.help_text }}</p>#}
{#                    {% endif %}#}
{##}
{##}
{#                    <button type="submit" class="btn btn-primary btn-block">注册</button>#}
{#                    <input type="hidden" name="next" value="{{ next }}">#}
{#                </form>#}
{#                <div class="flex-center top-gap text-small">#}
{#                    <a href="{% url 'login' %}">已有账号登录</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}



{% endblock users %}

myblog/templates/users/user_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block titile %}用户中心{% endblock titile %}
{% block top %}
    <link rel="stylesheet" href="{% static 'blog/css/user/user_style.css' %}">

{% endblock top %}
{% block breadcrumb %}
    <span class="separator">&#x2F;</span>
    <a href="{% url 'users:user_detail' %}">用户中心</a>
{% endblock breadcrumb %}
{% block users %}
{#    <div class="local-header"><h4>个人资料</h4></div>#}
{#    <form class="profile" method="post" enctype="multipart/form-data"#}
{#        action="{% url 'users:user_detail' %}">#}
{#        {% csrf_token %}#}
{#        {% crispy form %}#}
{##}
{#        <!--用户头像-->#}
{#        <div class="avatar">#}
{#            <img class="img-rounded" src="{{ request.user.avatar.url }}">#}
{#        </div>#}
{#        <button class="primaryAction" type="submit">更新资料</button>#}
{#    </form>#}

 <div class="widewrapper main">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 clean-superblock" id="contact">
                <h3>个人资料</h3>
                <form class="form" action="{% url 'users:user_detail' %}" method="post" enctype='multipart/form-data'>

                    {% csrf_token %}
                    {{ form.avatar.label_tag }}
                    <img src="{{ request.user.avatar.url }}" class="user_avatar">
                    <input style="border: none" id="id_avatar" name="avatar" type="file" value="上传头像">
                    {{ form.errors }}

                    <!-- 昵称 -->
                    {{ form.nickname.label_tag }}
                    {{ form.nickname }}
                    {{ form.errors }}


                    <!-- 用户邮箱 -->
                    {{ form.email.label_tag }}
                    {{ form.email }}
                    {{ form.errors }}
                    <div class="login_bottom">
                        <button type="submit" class="btn btn-primary btn-block">确认修改</button>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}">
                </form>
            </div>
        </div>
    </div>
</div>








{#<div class="flex-center">#}
{#    <div class="container">#}
{#        <div class="flex-center">#}
{#            <div class="unit-1-2 unit-1-on-mobile">#}
{#                <h3>用户中心</h3>#}
{#                <form class="form" action="{% url 'users:user_detail' %}" method="post" enctype="multipart/form-data">#}
{##}
{#                    {% csrf_token %}#}
{#                    {{ form.avatar.label_tag }}#}
{#                    <img src="{{ request.user.avatar.url }}">#}
{#                    <input id="id_avatar" name="avatar" type="file" value="上传头像">#}
{#                    {{ form.errors }}#}
{##}
{#                    <!-- 昵称 -->#}
{#                    {{ form.nickname.label_tag }}#}
{#                    {{ form.nickname }}#}
{#                    {{ form.errors }}#}
{##}
{##}
{#                    <!-- 用户邮箱 -->#}
{#                    {{ form.email.label_tag }}#}
{#                    {{ form.email }}#}
{#                    {{ form.errors }}#}
{#                     <button type="submit" class="btn btn-primary btn-block">确认修改</button>#}
{#                    <input type="hidden" name="next" value="{{ next }}">#}
{#                </form> #}
{##}
{#                    {% for field in form %}#}
{#                        {{ field.label_tag }}#}
{#                        {{ field }}#}
{#                        {{ field.errors }}#}
{#                        {% if field.help_text %}#}
{#                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}
{#                     <button type="submit" class="btn btn-primary btn-block">确认修改</button>#}
{#                    <input type="hidden" name="next" value="{{ next }}">#}
{#                </form>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}


{% endblock users %}