myblog/blog/urls.py
from django.conf.urls import url, handler404, handler500
from blog import views

app_name = 'blog'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'post/all/$', views.PostView.as_view(), name='post'),
    url(r'post/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'post/category/(?P<pk>\d+)/$', views.CategoryView.as_view(), name='category'),
    url(r'post/tag/(?P<pk>\d+)/$', views.TagView.as_view(), name='tag'),

]

handler404 = views.page_not_found
handler500 = views.page_error

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostRessFeed
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^15910/fly-admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^all/rss/$', AllPostRessFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^markdownx/', include('markdownx.urls')),

# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 ]

myblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
from myblog.settings import AUTH_USER_MODEL
import markdown
from markdownx.models import MarkdownxField
# Create your models here.


# =========================分---类====================================
class Category(models.Model):

    name = models.CharField(max_length=100, help_text='类别')

    def __str__(self):
        return self.name


class Tag(models.Model):

    name = models.CharField(max_length=100, help_text='标签名')

    def __str__(self):
        return self.name

# ===============================文---章====================================


class Post(models.Model):

    title = models.CharField(max_length=100, help_text='文章名')
    # body = models.TextField(help_text='文章内容')
    body = MarkdownxField(help_text='文章内容')
    created_time = models.DateTimeField(help_text='创建时间')
    modified_time = models.DateTimeField(auto_now=True, help_text='修改/更新时间')
    excerpt = models.CharField(max_length=200, blank=True, help_text='摘要')
    is_delete = models.BooleanField(default=False, help_text='删除标记')
    title_img = models.ImageField(upload_to='title_img/', default='title_img/default.jpg', help_text='标题图片')

    views = models.PositiveIntegerField(default=0, help_text='文章阅读量')

    category = models.ForeignKey(Category, help_text='类别')
    tag = models.ManyToManyField(Tag, help_text='标签')
    author = models.ForeignKey(AUTH_USER_MODEL, help_text='作者')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    # 增加阅读量
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',

        ])

        self.excerpt = strip_tags(md.convert(self.body))[:150]+'...'
        '''
        # print(self.title_img.name+'11111=============')
        # 上传图片时判断，上传时name为'文件名' split后长度为1
        # 此时加上title拼接成'title/文件名'
        # 当调用父类的save时 会生成'upload_to/title/文件名/'
        # 此后当访问页面时 调用到此save方法会在原有基础上不断加title
        # 因此当split ！= 1 时，直接调用原来的save便可
        if len(self.title_img.name.split('/')) == 1:
            # 将上传的文章标题图片保存到其id的文件夹下
            self.title_img.name = str(self.pk)+'/'+self.title_img.name
        # print(self.title_img.name)
        '''

        super(Post, self).save()

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Category, Tag
import markdown
from django.views.generic import ListView
from utils.pagination import pagination_data

# Create your views here.

# ==========================首页=========================================

# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     post_list = [post_list[i:i+2] for i in range(0, len(post_list), 2)]
#     return render(request, 'blog/index.html', {'post_list': post_list})


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 4

    def get_queryset(self):
        post = super(IndexView, self).get_queryset().order_by('-created_time')
        post = [post[i:i+2] for i in range(0, len(post), 2)]
        return post

    def get_context_data(self, **kwargs):
        # 获取父类生成的传递给模板的字典
        context = super(IndexView, self).get_context_data()
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 获取显示分页范围page_range，并加入到字典
        data = pagination_data(paginator, page, is_paginated)
        context.update(data)

        return context


class PostView(ListView):
    model = Post
    template_name = 'blog/post.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        post = super(PostView, self).get_queryset().order_by('-created_time')
        return post

    def get_context_data(self, **kwargs):
        # 获取父类生成的传递给模板的字典
        context = super(PostView, self).get_context_data()
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 获取显示分页范围page_range，并加入到字典
        data = pagination_data(paginator, page, is_paginated)
        context.update(data)

        return context

# ===================详情页==================================================


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    post.body = markdown.markdown(post.body, extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                 ])

    return render(request, 'blog/detail.html', {'post': post})


# =========================归档==================================================
# def archives(request, year, month):
#     post_list = Post.objects.filter(created_time__year=year, created_time__month=month).order_by('-created_time')
#     return render(request, 'blog/post.html', {'post_list': post_list})
class ArchivesView(ListView):
    model = Post
    template_name = 'blog/post.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year, created_time__month=month).\
            order_by('-created_time')

    def get_context_data(self, **kwargs):
        # 获取父类传递给模板的字典
        context = super(ArchivesView, self).get_context_data()
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 获取显示分页范围pag_range，更新入字典
        data = pagination_data(paginator, page, is_paginated)
        context.update(data)

        # 获取当前页类型，更新入字典
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        page_name = {'page_name': year+'年'+month+'月'}
        context.update(page_name)
        return context

# =================================分类======================================
# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request, 'blog/post.html', {'post_list': post_list})


class CategoryView(ListView):
    model = Post
    template_name = 'blog/post.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate).order_by('-created_time')

    def get_context_data(self, **kwargs):
        # 获取父类传递给模板的字典
        context = super(CategoryView, self).get_context_data()
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 获取显示分页范围page_range，更新入字典
        data = pagination_data(paginator, page, is_paginated)
        context.update(data)

        # 获取当前页类型，更新入字典
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        page_name = {'page_name': cate.name}
        context.update(page_name)
        return context


# ================================标签===========================================


class TagView(ListView):
    model = Post
    template_name = 'blog/post.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tag=tag).order_by('-created_time')

    def get_context_data(self, **kwargs):
        # 获取父类传递给模板的字典
        context = super(TagView, self).get_context_data()
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 获取显示分页范围page_range,更新入字典
        data = pagination_data(paginator, page, is_paginated)
        context.update(data)

        # 获取当前页类型，更新入字典
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        page_name = tag.name
        context.update({'page_name': page_name})
        return context


# ==========================404 500 403=====================
def page_not_found(request):
    return render(request, '404.html')


def page_error(request):
    return render(request, '500.html')

myblog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>About Me</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
 

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css">

    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600|PT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link rel="stylesheet" href="css/style.css" id="theme-styles">

    <!--[if lt IE 9]>      
        <script src="js/vendor/google/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->
    
</head>
<body>
    <header>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="index.html" id="logo">
                    <img src="img/logo.png" alt="clean Blog">
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".clean-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right clean-nav">
                    <div class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">
                          
                             <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>
                                <a href="about.html">About</a>
                            </li>
                            <li>
                                <a href="contact.html">Contact</a>
                            </li>                   
                        </ul>
                    </div>
                </nav>        

            </div>
        </div>

        <div class="widewrapper subheader">
            <div class="container">
                <div class="clean-breadcrumb">
                    <a href="#">About Me</a>
                </div>

                <div class="clean-searchbox">
                    <form action="#" method="get" accept-charset="utf-8">
                       
                        <input class="searchfield" id="searchbox" type="text" placeholder="Search">
                         <button class="searchbutton" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="widewrapper main">
        <div class="container about">
            <h1>Hello, My name is <span class="about-bold">  John Doe</span></h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus inventore magni ratione perferendis ex molestiae cum reiciendis perspiciatis consequuntur, nihil ducimus corrupti! Ipsum nesciunt ipsa nobis obcaecati labore, rem recusandae?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui quo sint asperiores, ut doloremque eum commodi, odit nisi sed repellendus earum recusandae pariatur consectetur minus rerum, magni dolores officiis magnam.</p>

            <div class="about-button">
                <a class="btn btn-xlarge btn-clean-one" href="contact.html">Contact Me</a>
            </div>
            <hr>
        </div>

    </div>

    <footer>
        <div class="widewrapper footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-user"></i>About</h3>

                       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab animi laboriosam nostrum consequatur fugiat at, labore praesentium modi, quasi dolorum debitis reiciendis facilis, dolor saepe sint nemo, earum molestias quas.</p>
                       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum, error aspernatur assumenda quae eveniet.</p>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-pencil"></i> Recent Post</h3>
                        <ul class="clean-list">
                            <li><a href="">Clean - Responsive HTML5 Template</a></li>
                            <li><a href="">Responsive Pricing Table</a></li>
                            <li><a href="">Yellow HTML5 Template</a></li>
                            <li><a href="">Blackor Responsive Theme</a></li>
                            <li><a href="">Portfolio Bootstrap Template</a></li>
                            <li><a href="">Clean Slider Template</a></li>
                        </ul>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-envelope"></i>Contact Me</h3>

                        <p>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil fugiat, cupiditate veritatis excepturi tempore explicabo.</p>
                         <div class="footer-widget-icon">
                            <i class="fa fa-facebook"></i><i class="fa fa-twitter"></i><i class="fa fa-google"></i>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
        <div class="widewrapper copyright">
                Copyright 2015
        </div>
    </footer>
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/modernizr.js"></script>

</body>
</html>

myblog/templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load threadedcomments_tags %}
{% block titile %}{{ post.title }}{% endblock titile %}

{% block top %}
<script src="{% static 'mycomments/js/test.js' %}"></script>
{% endblock top %}
{% block breadcrumb %}
    <span class="separator">&#x2F;</span>
    <a href="{% url 'blog:post' %}">文章</a>
    <span class="separator">&#x2F;</span>
    <a href="{% url 'blog:category'  post.category_id %}">{{ post.category}}</a>
    <span class="separator">&#x2F;</span>
    <a href="#">{{ post.title }}</a>
{% endblock breadcrumb %}



{% block main %}


<article class="blog-post">
    <header>
       
        <div class="lead-image">
            <img src="{{ post.title_img.url }}" alt="" class="img-responsive">
            
        </div>
    </header>
    <div class="body">
        <h1>{{ post.title }}</h1>
        <div class="meta">
            <i class="fa fa-calendar"></i>{{ post.created_time }}

            <i class="fa fa-eye"> </i>{{ post.views }}&nbsp;
            <i class="fa fa-comments"></i>
            <span ><a href="#comments">{{ comment_list|length }}</a></span>&nbsp;
            <i class="fa fa-tags" style="font-size: 15px"></i>
            <span >
                {% for tag in post.tag.all %}
                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                {% endfor %}
            </span>

        </div>

        {{ post.body |safe }}
    </div>
</article>

<aside class="social-icons clearfix">

<table  border="0" align="center">
<tr>
<td>    <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more">分享到：</a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间">QQ空间</a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信">微信</a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博">新浪微博</a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网">人人网</a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博">腾讯微博</a></div>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"16"},"share":{"bdSize":16}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
</td>
</tr>
</table>





{#    <h3>Share on </h3>#}
{#    <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-google"></i></a>#}
</aside>

    {% render_comment_list for post %}



<aside class="comments" id="comments">
<hr>


    <h2><i id="add_comment" class="fa fa-pencil"></i> 添 加 评 论  </h2>
    {% if user.is_authenticated %}
    {% render_comment_form for post %}

    {% else %}

    <div style="text-align: center">
        需要<a href="{% url 'login' %}?next={{ request.path | slice:':-1'}}#add_comment" style="color: #337ab7">登录</a>之后才能评论哦 (*^__^*)
    </div>
    {% endif %}
</aside>




{% endblock main %}

myblog/templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block titile %}fly's Blog{% endblock titile %}
{% block main %}
{% for post in post_list %}
<div class="row">
    <div class="col-md-6 col-sm-6">
        <article class="blog-teaser">
            <header>
                <img src="{{ post.0.title_img.url }}" alt="">
                <h3><a href="{{ post.0.get_absolute_url }}">{{ post.0.title }}</a> </h3>
                <span class="meta">{{ post.0.created_time }} &nbsp;  浏览:{{ post.0.views }}  </span>
                <p style="color: #5b6268;">
                    分类 : <a href="{% url 'blog:category' post.0.category_id %}">{{ post.0.category }}</a> &nbsp;
                    标签 :{% for tag in post.0.tag.all %}
                        <a href="{% url 'blog:tag' tag.id %}">{{ tag.name }}</a>
                        {% endfor %}

                </p>

                <hr>
            </header>
            <div class="body" >
                <p style="text-align: justify">
                {{ post.0.excerpt }}
                </p>
            </div>
            <div class="clearfix">
                <a href="{{ post.0.get_absolute_url }}" class="btn btn-clean-one">阅读全文</a>
            </div>
        </article>
    </div>
    {% if post.1 %}
    <div class="col-md-6 col-sm-6">
        <article class="blog-teaser">
            <header>
                <img src="{{ post.1.title_img.url }}" alt="">
                <h3><a href="{{ post.1.get_absolute_url }}">{{ post.1.title }}</a></h3>
                <span class="meta">{{ post.1.created_time }} &nbsp;  浏览:{{ post.1.views }}  </span>
                 <p style="color: #5b6268;">
                    分类 : <a href="{% url 'blog:category' post.1.category_id %}">{{ post.1.category }}</a> &nbsp;
                    标签 : {% for tag in post.1.tag.all %}
                        <a href="{% url 'blog:tag' tag.id %}">{{ tag.name }}</a>
                        {% endfor %}

                </p>
                <hr>
            </header>
            <div class="body">
                {{ post.1.excerpt }}
            </div>
            <div class="clearfix">
                <a href="{{ post.1.get_absolute_url }}" class="btn btn-clean-one">阅读全文</a>
            </div>
        </article>
    </div>
    {% endif %}
</div>

{% endfor %}




    <div class="text-center">
    <nav aria-label="Page navigation ">
  <ul class="pagination " style="margin-bottom: 0">

  {% if is_paginated %}

    {% if page_obj.number != 1 %}
    <li>
      <a href="?page=1" aria-label="首页">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
    {% endif %}

    {% for i in page_range %}

        {% if i == page_obj.number %}
            <li class="active"><a href="?page={{ i }}">{{ i }}</a></li>
        {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">下一页</a></li>
    {% endif %}
    {% if page_obj.number != paginator.num_pages  %}
    <li>
      <a href="?page={{ paginator.num_pages }}" aria-label="最后一页">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  {% endif %}

  </ul>
    <div class="text-center">第&nbsp;{{ page_obj.number }}&nbsp;/&nbsp;{{ paginator.num_pages }}&nbsp;页</div>
</nav>
    </div>
{% endblock main %}

myblog/templates/blog/post.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block breadcrumb %}
    <span class="separator">&#x2F;</span>
    <a href="{% url 'blog:post' %}">文章</a>
    {% if page_name %}
    <span class="separator">&#x2F;</span>
    <a href="#">{{ page_name }}</a>
    {% endif %}
{% endblock breadcrumb %}




{% block main %}
<div class="row">
    {% for post in post_list %}
    <div class="col-md-12 col-sm-12">
        <article class="">
         <div class="" style="border: 0;">
            <header>
                <h3><a style="color: #454a4e;text-align: center" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                <p class="text-muted" style="">
                 <small>发布时间:{{ post.created_time }}</small>
                 <small class="" style="margin-left: 20px">
                 阅读量: <span class="badge">{{ post.views }}</span>
                 </small>
                </p>
            </header>
            <div class="body" style="margin-bottom: 10px; min-height: 135px">

                <div style="height: 100%;min-height: 135px;width: 200px;float: right;margin-left: 8px">
                    <a href="{{ post.get_absolute_url }}" style="width: 100%;height: 100%">
                        <img src="{{ post.title_img.url }}" style="width: 100%;height: 100%;min-height: 135px  ">
                    </a>
                </div>
                <p style="text-align: justify; min-height: 115px">
                {{ post.excerpt }}
                </p>
            </div>
            <p style="font-size: 12px">
                类别：<a href="{% url 'blog:category' post.category_id %}"><span class="badge">{{ post.category.name }}</span></a>
                &nbsp;
                标签：
                {% for tag in post.tag.all %}
                    <a href="{% url 'blog:tag' tag.id %}"><span class="badge">{{ tag.name }}</span></a>
                {% endfor %}
            </p>
            </div>
   <div style="border: 1px dashed #ddd;"></div>
        </article>
    </div>
    {% empty %}
        暂时还没发布文章
  {% endfor %}
</div>

<div class="text-center">
    <nav aria-label="Page navigation ">
  <ul class="pagination " style="margin-bottom: 0">

  {% if is_paginated %}
    {% if page_obj.number != 1 %}
    <li>
      <a href="?page=1" aria-label="首页">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
    {% endif %}

    {% for i in page_range %}

        {% if i == page_obj.number %}
            <li class="active"><a href="?page={{ i }}">{{ i }}</a></li>
        {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">下一页</a></li>
    {% endif %}
    {% if page_obj.number != paginator.num_pages  %}
    <li>
      <a href="?page={{ paginator.num_pages }}" aria-label="最后一页">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  {% endif %}

  </ul>
    <div class="text-center">第&nbsp;{{ page_obj.number }}&nbsp;/&nbsp;{{ paginator.num_pages }}&nbsp;页</div>
</nav>
    </div>
{% endblock main %}