myblog/blog/urls.py
from django.conf.urls import url, handler404, handler500
from blog import views

app_name = 'blog'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'post/all/$', views.PostView.as_view(), name='post'),
    url(r'post/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'post/category/(?P<pk>\d+)/$', views.CategoryView.as_view(), name='category'),
    url(r'post/tag/(?P<pk>\d+)/$', views.TagView.as_view(), name='tag'),

]

handler404 = views.page_not_found
handler500 = views.page_error

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostRessFeed
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^15910/fly-admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^all/rss/$', AllPostRessFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^markdownx/', include('markdownx.urls')),

# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 ]

myblog/mycomments/forms.py
from crispy_forms.helper import FormHelper
from threadedcomments.forms import ThreadedCommentForm


class MyCommentForm(ThreadedCommentForm):

    '''
        My Customized Comment Form.
        Just add some features via crispy.
    '''

    #: Helper for {% crispy %} template tag
    helper = FormHelper()
    helper.form_tag = False

myblog/mycomments/templates/comments/form.html
{% load comments i18n crispy_forms_tags %}
{#{% get_comment_form for post as blog_form  %}#}
<!-- 评论表单 -->
{#{% if user.is_authenticated %}#}
<div id="wrap-form-comment">
    <div class="well" id="form-comment">
        <h4>评论:</h4>
        <form role="form" id="myform" action="{% comment_form_target %}" method="post">
        {% csrf_token %}
         {{form.content_type}}{{form.object_pk}}{{form.timestamp}}{{form.security_hash}}

        {% if next %}
            <div><input type="hidden" name="next" value="{{ next }}"/></div>
        {% endif %}
{##}
            <textarea style="width: 100%;resize: vertical" rows="5"  id="id_comment" name="comment" placeholder="快输入你机智的评论吧o(≧v≦)o~~" class="form-control input-lg"></textarea>
            <br>
{#        {% crispy form %}#}
            <div style="text-align: right" id="P_tips">
                <div id="tips"  style="display: none;color: red;float: left;">(*•ω•)评论不能为空哦</div>
                <!--获取回复评论id-->
                <input id="id_parent" name="parent" type="hidden">
            <input type="button"  class="btn btn-primary" value="发表评论">
            <button id="cancel_reply"  type="button" class="btn btn-default">取消评论</button>
            <input type="hidden" name="next" value="{%url 'blog:detail' post.id%}"/>
            </div>
        </form>
    </div>
</div>
{#{% else %}#}
{#  <p>Please <a href="/login/">log in</a> to post comments.</p>#}
{#{% endif %}#}

myblog/mycomments/templates/comments/list.html
{% load threadedcomments_tags %}
{% load staticfiles %}
<aside class="comments" style="margin-bottom: 50px" >
    <hr>
    {% if comment_list|length > 0 %}
    <h2><i class="fa fa-comments"></i> {{ comment_list|length }}&nbsp;Comments</h2>

{#{% for comment in comment_list|fill_tree|annotate_tree %}#}
{#    {% ifchanged comment.parent_id %}{% else %}</li>{% endifchanged %}#}
{#    {% if not comment.open and not comment.close %}</li>{% endif %}#}
{#    {% if comment.open %}<ul>{% endif %}#}
{##}
{#    <li id="c{{ comment.id }}">#}
{#        ...#}
{#    {% for close in comment.close %}</li></ul>{% endfor %}#}
{#{% endfor %}#}


    {% for comment in comment_list|fill_tree|annotate_tree %}
    {% if not comment.parent_id %}
    <article class="comment" id=c{{ comment.id }}>
        <header class="clearfix" >
            <img src="{{ comment.user.avatar.url }}"  alt="A Smart Guy" class="avatar">
            <div class="meta">
                <h4><a href="#">{{ comment.user.nickname }}</a></h4>
                <span class="date">{{ comment.submit_date }}</span>
                <span class="separator">-</span>
                <a href="#c{{ comment.id }}" data-comment-id="{{ comment.id }}" class="reply-link" >Reply</a>
            </div>
        </header>

        <div class="body"  >
            {{ comment.comment}}
        </div>

     </article>
{#            <ul>#}
    {% else %}
            <article class="comment reply">
        <header class="clearfix">
            <img src="{{ comment.user.avatar.url }}" alt="A Smart Guy" class="avatar">
            <div class="meta">
                <h4><a href="#">{{ comment.user.nickname }}</a></h4>
                <span class="date">{{ comment.submit_date }}</span>
                <span class="separator">-</span>
                <a href="#c{{ comment.id }}" data-comment-id="{{ comment.id }}" class="reply-link">Reply</a>
            </div>
        </header>
        <div class="body" id="c{{ comment.id }}">
            {{ comment.comment}}    
        </div>
    </article>
{#            else</li>#}

        {% endif %}
{#        <div id="c{{ comment.id }}"></div>#}


{#            {% for colse in comment.close %}</li>close</ul>{% endfor %}#}

    {% endfor %}

{% else %}

    <h2 ><i class="fa fa-comments"></i>暂无评论，智慧的你快来评论吧～</h2>
{% endif %}
</aside>
{##}
{#    <article class="comment reply">#}
{#        <header class="clearfix">#}
{#            <img src="{% static 'blog/img/avatar.png' %}" alt="A Smart Guy" class="avatar">#}
{#            <div class="meta">#}
{#                <h3><a href="#">{{ comment.user.nickname }}</a></h3>#}
{#                <span class="date">{{ comment.submit_date }}</span>#}
{#                <span class="separator">-</span>#}
{#                <a href="#c{{ comment.id }}" data-comment-id="{{ comment.id }}" class="reply-link">Reply</a>#}
{#            </div>#}
{#        </header>#}
{#        <div class="body">#}
{#            {{ comment.comment}}#}
{#        </div>#}
{#    </article>#}